// saga actions 정의
export const sagaActions = {
  FETCH_POSTS: 'POST/FETCH_POSTS',
  CREATE_POST: 'POST/CREATE_POST',
  UPDATE_POST: 'POST/UPDATE_POST',
  DELETE_POST: 'POST/DELETE_POST',
  RESET_FORM: 'FORM/RESET_FORM',
  FETCH_TODOS: 'TODO/FETCH_TODOS',
  CREATE_TODO: 'TODO/CREATE_TODO',
  DELETE_TODO: 'TODO/DELETE_TODO',
  TOGGLE_TODO: 'TODO/TOGGLE_TODO'
};
